# Inspired by panopoly: https://github.com/panopoly/panopoly/blob/7.x-1.x/.travis.yml

language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null


install:

  # Add the Google Chrome packages.
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update > /dev/null

  # Create drupal database
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --prefer-source --no-interaction drush/drush:6.*

  # Set up drush aliases
  - mv .drush $HOME/

  # Fix host authenticity issue
  - echo -e "Host code.osu.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  # Get the platform
  - drush @testing make --yes --prepare-install build-eng.make drupal

  # Build Behat dependencies
  - cd drupal/profiles/eng/tests/behat
  - composer install --prefer-source --no-interaction

  # Get webdrivercss dependencies
  - cd ../webdrivercss
  - npm install

  # Setup files
  - cd ../../../../../
  - sudo chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

    # Get Chrome and ChromeDriver
  - sudo apt-get install google-chrome-stable
  - wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
  - unzip -a chromedriver_linux64.zip

  # Insane hack from jsdevel:
  #   https://github.com/jsdevel/travis-debugging/blob/master/shim.bash
  # This allows chrome-sandbox to work in side of OpenVZ, because I can't
  # figure out how to start chrome with --no-sandbox.
  - export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox
  - sudo rm -f $CHROME_SANDBOX
  - sudo wget https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE -O $CHROME_SANDBOX
  - sudo chown root:root $CHROME_SANDBOX; sudo chmod 4755 $CHROME_SANDBOX
  - sudo md5sum $CHROME_SANDBOX

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar
  - java -jar selenium-server-standalone-2.41.0.jar -Dwebdriver.chrome.driver=`pwd`/chromedriver > /dev/null 2>&1 &
  - sleep 5

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:

  # Do the site install
  - cd drupal/sites/default
  - drush @testing si eng --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Eng build" --yes -v

  # Disable shibboleth
  - drush @testing vset osu_authentication_redirect_auth_to_shib FALSE

  # Install some demo content.
  - drush @testing dl panopoly_demo -y
  - drush @testing en panopoly_demo -y

  # start a web server on port 80, run in the background; wait for initialization
  - drush @testing rs --php-cgi=`which php-cgi` 8080 > /dev/null 2>&1 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done
  - cd ../../profiles/eng/tests

script:
  - cd behat
  - ./bin/behat --config behat.travis.yml
  - cd ../webdrivercss
  - npm test

after_sucess:
# put deployment code here
