# Inspired by panopoly: https://github.com/drupalprojects/panopoly/blob/7.x-1.x/.travis.yml

language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # For testing
  - echo 'travis build directory'
  - echo $TRAVIS_BUILD_DIR
  - sudo apt-get update > /dev/null
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:6.*

  # Fix host authenticity issue
  - echo -e "Host code.osu.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  # Get the platform
  - drush make --yes --prepare-install build-eng.make drupal

    # Build Behat dependencies
  - cd drupal/profiles/eng/tests/behat
  - composer install --prefer-source --no-interaction
  - cd ../../../../../

  # Setup files
  #- sudo chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar
  - java -jar selenium-server-standalone-2.37.0.jar > /dev/null 2>&1 &
  - sleep 5

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:

  # Make the Travis tests repos agnostic by injecting drupal_root with BEHAT_PARAMS
  # - BUILD_OWNER=`dirname $TRAVIS_BUILD_DIR`
  - export BEHAT_PARAMS="extensions[Drupal\\DrupalExtension\\Extension][drush][root]=$TRAVIS_BUILD_DIR/drupal"

  # Do the site install
  - cd drupal/sites/default
  - drush si eng --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Eng build" --yes -v

  # Start the server
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - sleep 3
  - cd ../../profiles/eng/tests/behat

script:

  - ./bin/behat --config behat.travis.yml
