# Inspired by panopoly: https://github.com/drupalprojects/panopoly/blob/7.x-1.x/.travis.yml

language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

install:
  # Create drupal database
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --prefer-source --no-interaction drush/drush:6.*

  # Set up drush aliases
  - mv .drush $HOME/

  # Fix host authenticity issue
  - echo -e "Host code.osu.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  # Get the platform
  - drush make --yes --prepare-install build-eng.make drupal

    # Build Behat dependencies
  - cd drupal/profiles/eng/tests/behat
  - composer install --prefer-source --no-interaction
  - cd ../../../../../

  # Setup files
  #- sudo chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar
  - java -jar selenium-server-standalone-2.37.0.jar > /dev/null 2>&1 &
  - sleep 5

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:

  # Do the site install
  - cd drupal/sites/default
  - drush si eng --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Eng build" --yes -v

  # start a web server on port 80, run in the background; wait for initialization
  - drush runserver --server=builtin 8080 &
  #- drush runserver --php-cgi=php5-cgi --dns localhost:8888 > /dev/null 2>&1 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done
  - cd ../../profiles/eng/tests/behat

  - drush @testing status

  # testing site connection
  - curl -I http://127.0.0.1:8080

script:

  - ./bin/behat --config behat.travis.yml

after_sucess:
# put deployment code here
